### ISSUE TITLE
BrazilJS

### ISSUE THREAD

**Issue by robsonbittencourt** [devnaestrada/community#5]
Acho que seria interessante entrevistar o pessoal da BrazilJS, @jaydson e o @felipenmoura para que eles falassem mais como surgiu a iniciativa. Além disso falar sobre como isso se tornou o novo trabalho deles, e como é organizar outros eventos como o FrontInPoa.

**Comment by raymonsanches** [comment]
É uma boa sugestão @robsonbittencourt, mas acho que isso caberia mais como uma pauta mais trabalhada. Mas podemos ver sim. Mas aqui pro Community, acho que não seria o caso

;)
